name: CICD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-latest
    environment: 
      name: Development
    steps:
      - name: Add NuGet Private Source
        run: | 
              dotnet nuget add source --username mirodmarinov --password "${{secrets.NUGET_ACCESS_TOKEN}}" --store-password-in-clear-text --name githubNuget "https://nuget.pkg.github.com/diversiwaver/basedataaccess/index.json"
              dotnet nuget list source
              dotnet list package
              
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'
      - name: Restore NuGet Packages
        run: |
          dotnet nuget list source
          dotnet list package
          dotnet restore --verbosity detailed
      - name: Build
        shell: bash
        run: |
          dotnet tool install --global dotnet-releaser
          dotnet-releaser build --github-token "${{secrets.NUGET_ACCESS_TOKEN}}" src/dotnet-releaser-build.toml
  DeployDev:
    name: Deploy to Development
    runs-on: windows-latest
    environment: 
      name: Development
    needs: [Build]
    steps:
      - name: Add NuGet Private Source
        run: dotnet nuget add source --username mirodmarinov --password "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" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/diversiwaver/index.json"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'
      - name: Restore NuGet Packages
        run: dotnet restore
      - name: Test
        shell: bash
        run: |
          dotnet tool install --global dotnet-releaser
          dotnet-releaser run --github-token "${{secrets.NUGET_ACCESS_TOKEN}}" src/dotnet-releaser-test.toml
  DeployProd:
    name: Deploy to Production 
    needs: [DeployDev]
    runs-on: windows-latest
    environment: 
      name: Production
    steps:
      - name: Add NuGet Private Source
        run: dotnet nuget add source --username diversiwaver --password "${{secrets.NUGET_ACCESS_TOKEN}}" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/diversiwaver/index.json"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'
      - name: Restore NuGet Packages
        run: dotnet restore
      - name: Release & Publish Nuget Packages
        shell: bash
        run: |
          dotnet tool install --global dotnet-releaser
          dotnet-releaser publish --github-token "${{secrets.GITHUB_TOKEN}}" --nuget-token "${{secrets.NUGET_TOKEN}}" src/dotnet-releaser-release.toml
